name = "just-sticky-notes-4"
main = "worker.js"
compatibility_date = "2024-01-01"

# R2 버킷 바인딩
[[r2_buckets]]
binding = "STICKY_NOTES_BUCKET"
bucket_name = "just-sticky-notes-storage"

# 환경 변수
[vars]
ENVIRONMENT = "production" 